const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv') .config();
const authRoutes = require('./routes/Routes');
const postRoutes = require('./routes/postRoutes');
const commentRoutes = require('./routes/commentRoutes');
const dashboardRoutes = require("./routes/dashboardRoutes");
const app =express();
app.use(cors());
app.use(express.json());
app.use('/api/auth',authRoutes);
app.use('/api/posts', postRoutes);
app.use('/api/comments', commentRoutes);
app.use("/api/dashboard", dashboardRoutes);
mongoose.connect(process.env.MONGO_URI).then(() => console.log('mongoDB connected')) .catch((err) => console.log(err));
app.listen(process.env.PORT, () => { console.log(`Server running on port ${process.env.PORT}`);});
